#!/command/with-contenv /bin/bash

set -eo pipefail

[[ $DEBUG == true ]] && set -x

if [ ! -d /home/user/vnc ]; then
	mkdir /home/user/.vnc
fi
chown -R user:user /home/user/.vnc
chmod -R 755 /home/user/.vnc
if [ "$VNC_PASSWD" != '' ]; then
	# set vnc password
	echo -e "$VNC_PASSWD\n$VNC_PASSWD\n\n" | sudo -Hu user vncpasswd /home/user/.vnc/passwd
fi

if [ ! -d /etc/vnc ]; then
	mkdir /etc/vnc
fi
echo 'openbox-session' > /etc/vnc/xstartup

# Clear X lock.
# Some container host (e.g. hyper.sh) will keep /tmp even after a restart.
if [ -f /tmp/.X11-lock ]; then
	rm -f /tmp/.X11-lock
fi
