#!/usr/bin/with-contenv bash
if [ "$VNC_PASSWD" != '' ]; then
	echo "[tigervnc-service] vnc authentication enabled"
	sudo -Hu user /usr/bin/vncserver :11 -fg -geometry $VNC_GEOMETRY -depth 24
else
	echo "[tigervnc-service] vnc authentication disabled"
	sudo -Hu user /usr/bin/vncserver :11 -fg -geometry $VNC_GEOMETRY -depth 24 -SecurityTypes None
fi
