name: push_to_dockerhub_2204

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build 和 push arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.arm64-2204
          platforms: linux/arm64
          push: true
          tags: lhpmain/docker-novnc:latest-arm64-2204, lhpmain/docker-novnc:arm64-2204
      -
        name: Build 和 push amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.amd64-2204
          platforms: linux/amd64
          push: true
          tags: lhpmain/docker-novnc:latest-2204, lhpmain/docker-novnc:latest-amd64-2204, lhpmain/docker-novnc:amd64-2204
